.TH pdiffjson 1 "April 2020" "0.2" ""
.SH NAME
pdiffjson \- diff JSON the easy way

.SH SYNOPSIS
pdiffjson [diff options] file1.json file2.json

.SH DESCRIPTION
Show colored diff of pretty-printed, normalized JSON. Uses less to
paginate the output. Allows a readable diff of any JSON, ignoring all
non-semantic whitespace.

This is a "semi-structural diff", meaning it only shows structural
(semantic) changes but is done syntactically on JSON output, which
actually makes it more readable and flexible than a true structural
diff. Works on large files since it relies only on diff and jq.
Keys are sorted before calling diff, so ordering of keys in collections
is ignored (as it should be).

Expects to be used from a terminal with color support.

By default calls diff without arguments, yielding a unified diff. But
it can be helpful to add standard diff arguments to refine the type of
output, such as:
-c (contextual diff),
-C2 (contextual diff with two lines of context), or
-U5 (unified diff with 5 lines of context).

.SH OPTIONS
Options are the same as diff(1).

.SH SEE ALSO
diff(1), colordiff(1), less(1), jq

.SH AUTHOR
Joshua Levy (joshua@cal.berkeley.edu)
