.TH pjson 1 "April 2020" "0.2" ""
.SH NAME
pjson \- display JSON the easy way

.SH SYNOPSIS
pjson [file]

.SH DESCRIPTION
Show colored, pretty-printed, normalized JSON, paginated with less(1).
A one-liner to make it easier to browse JSON files of any size.

If no file provided, reads from stdin.

.SH OPTIONS
None.

.SH SEE ALSO
less(1), jq

.SH AUTHOR
Joshua Levy (joshua@cal.berkeley.edu)
