#!/bin/bash

set -euo pipefail

if [[ $# < 2 ]]; then
  echo "Usage: $(basename $0) [diff options] file1.json file2.json

Show diff of pretty-printed, normalized, colorized JSON. Uses less to
paginate the output. Allows a readable diff of any JSON, ignoring all
non-semantic whitespace.

This is a "semi-structural diff", meaning it only shows structural
(semantic) changes but is done syntactically on JSON output, which
actually makes it more readable and flexible than a true structural
diff. Works on large files since it relies only on diff and jq.
Keys are sorted before calling diff, so ordering of keys in collections
is ignored (as it should be).

By default calls diff without arguments, yielding a unified diff. But
it can be helpful to add standard diff arguments to refine the type of
output, such as:
  -c (contextual diff)
  -C2 (contextual diff with two lines of context)
  -U5 (unified diff with 5 lines of context)"

  exit 1
fi

# Last two args are the two files. Other options are passed to diff.
file1="${@:(-2):1}"
file2="${@:(-1):1}"
num_diff_opts=$(($#-2))

if [[ ! -f "$file1" ]]; then
  echo "not a file: $file1"
  exit 1
fi
if [[ ! -f "$file2" ]]; then
  echo "not a file: $file2"
  exit 1
fi

diff ${@:1:$num_diff_opts} <(jq --sort-keys . < "$file1") <(jq --sort-keys . < "$file2") | colordiff | less -R
